package billing

import "github.com/prometheus/client_golang/prometheus"

// Outcome labels for billing_renewer_run_total. The metric is per-
// subscription (one increment per row processed by Tick), not per-tick,
// because per-tick counts hide the inner distribution between renewals
// and skips.
const (
	OutcomeSuccess            = "success"
	OutcomeSkippedAlreadyDone = "skipped_already_done"
	OutcomeError              = "error"
)

// Metrics is the Prometheus surface the renewer exports. One instance
// is constructed at boot and passed to New(); tests build a private
// registry and assert via prometheus/testutil.
type Metrics struct {
	// Runs counts renewer outcomes per subscription processed. Labels:
	// outcome ∈ {success, skipped_already_done, error}.
	Runs *prometheus.CounterVec

	// Invoices counts invoices generated by the renewer. The state
	// label lives on the invoice (always "pending" for inserts the
	// renewer makes, but the label is kept so dashboards can pivot
	// alongside other invoice events that may be added later).
	Invoices *prometheus.CounterVec
}

// NewMetrics registers the renewer's counters on reg. reg may be nil
// for tests that want to construct the counters without registering.
func NewMetrics(reg prometheus.Registerer) *Metrics {
	m := &Metrics{
		Runs: prometheus.NewCounterVec(prometheus.CounterOpts{
			Name: "billing_renewer_run_total",
			Help: "Per-subscription renewer outcomes (success, skipped_already_done, error).",
		}, []string{"outcome"}),
		Invoices: prometheus.NewCounterVec(prometheus.CounterOpts{
			Name: "billing_invoice_generated_total",
			Help: "Invoices generated by the billing renewer, partitioned by invoice state.",
		}, []string{"state"}),
	}
	if reg != nil {
		reg.MustRegister(m.Runs, m.Invoices)
	}
	return m
}

func (m *Metrics) incRun(outcome string) {
	if m == nil {
		return
	}
	m.Runs.WithLabelValues(outcome).Inc()
}

func (m *Metrics) incInvoice(state string) {
	if m == nil {
		return
	}
	m.Invoices.WithLabelValues(state).Inc()
}
