#!/usr/bin/env bash
# scripts/update-config-and-redeploy.sh — semi-manual rotation driver
# for secrets whose new value is generated by an external provider's
# UI (SIN-63189). The operator pastes the new value on stdin (with
# echo disabled); the script writes it into the deploy env file,
# redeploys the affected service, validates, and emits the audit row.
#
# Companion docs:
#   docs/ops/secrets-rotation.md          — per-secret procedure
#   docs/ops/secret-rotation-schedule.md  — cadence calendar
#
# Usage:
#   scripts/update-config-and-redeploy.sh <name> [--dry-run] [--rollback]
#
# Names handled here:
#   openrouter      → OPENROUTER_API_KEY (full-stack restart)
#   pagarme         → PAGARME_API_KEY    (full-stack restart)
#   slack-alerts    → SLACK_ALERTS_WEBHOOK_URL (worker-only restart)
#
# Required environment (see secrets-rotation.md "Prerequisites"):
#   CRM_OPS_ACTOR_USER_ID, CRM_AUDIT_DSN, PGPASSWORD, CRM_DEPLOY_ENV_FILE
#
# Optional environment:
#   CRM_REDEPLOY_CMD     — override the per-secret default redeploy cmd.
#   CRM_DRY_RUN          — '1' = same as --dry-run.
#
# Exit codes:
#   0  cycle completed (or dry-run printed cleanly)
#   1  generic failure (validation, redeploy, audit insert)
#   2  rollback completed
#   64 usage error
#   69 missing prerequisite tool or env var
#
# Library mode: when UPDATE_CONFIG_LIB_ONLY=1 the script sources without
# executing main, so scripts/update-config-and-redeploy.test.sh can call
# the pure helpers directly.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEFAULT_ENV_FILE="${REPO_ROOT}/deploy/compose/.env"
CRM_DEPLOY_ENV_FILE="${CRM_DEPLOY_ENV_FILE:-$DEFAULT_ENV_FILE}"

MODE_DRY_RUN=0
MODE_ROLLBACK=0
SECRET_NAME=""

if [[ "${CRM_DRY_RUN:-0}" == "1" ]]; then
	MODE_DRY_RUN=1
fi

log()  { printf '[update-config] %s\n' "$*" >&2; }
warn() { printf '[update-config] WARN: %s\n' "$*" >&2; }
die()  { printf '[update-config] FATAL: %s\n' "$*" >&2; exit "${2:-1}"; }

redact() {
	if [[ -n "${1:-}" ]]; then
		printf '%s' '***REDACTED***'
	fi
}

require_env() {
	local var="$1"
	if [[ -z "${!var:-}" ]]; then
		die "missing required env var: $var" 69
	fi
}
require_cmd() {
	if ! command -v "$1" >/dev/null 2>&1; then
		die "missing required tool: $1" 69
	fi
}

# ----------------------------------------------------------------------
# Per-secret table — name → (env key, default redeploy cmd, validate fn)
# ----------------------------------------------------------------------

env_key_for() {
	case "$1" in
		openrouter)   echo "OPENROUTER_API_KEY" ;;
		pagarme)      echo "PAGARME_API_KEY" ;;
		slack-alerts) echo "SLACK_ALERTS_WEBHOOK_URL" ;;
		*)            return 1 ;;
	esac
}

default_redeploy_for() {
	local f="${REPO_ROOT}/deploy/compose/compose.yml"
	case "$1" in
		openrouter|pagarme)
			echo "docker compose -f $f up -d --no-deps app"
			;;
		slack-alerts)
			echo "docker compose -f $f up -d --no-deps wallet-alerter-worker"
			;;
		*) return 1 ;;
	esac
}

# ----------------------------------------------------------------------
# Pure helpers (library-safe)
# ----------------------------------------------------------------------

is_supported_name() {
	env_key_for "$1" >/dev/null 2>&1
}

audit_payload() {
	local name="$1" phase="$2" extra="${3:-}"
	printf '{"secret":"%s","phase":"%s"%s}' "$name" "$phase" "$extra"
}

validate_actor_uuid() {
	local u="$1"
	[[ "$u" =~ ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ ]]
}

# ----------------------------------------------------------------------
# I/O helpers
# ----------------------------------------------------------------------

emit_audit() {
	local name="$1" phase="$2" extra="${3:-}"
	local payload
	payload=$(audit_payload "$name" "$phase" "$extra")
	if (( MODE_DRY_RUN == 1 )); then
		log "[dry-run] audit emit: $payload"
		return 0
	fi
	require_env CRM_AUDIT_DSN
	require_env PGPASSWORD
	local sql
	sql=$(printf '%s' \
		"INSERT INTO audit_log_security (actor_user_id, event_type, target) " \
		"VALUES ('%s', 'key_rotation', %s::jsonb);")
	# shellcheck disable=SC2059
	sql=$(printf "$sql" "$CRM_OPS_ACTOR_USER_ID" "$(printf "%q" "$payload")")
	echo "$sql" | psql "$CRM_AUDIT_DSN" --quiet --no-psqlrc --set ON_ERROR_STOP=1 >/dev/null
	log "audit emit OK: $payload"
}

update_env_file() {
	local key="$1" value="$2"
	local f="$CRM_DEPLOY_ENV_FILE"
	if [[ ! -f "$f" ]]; then
		die "deploy env file not found: $f" 1
	fi
	if (( MODE_DRY_RUN == 1 )); then
		log "[dry-run] would update $f: ${key}=$(redact "$value")"
		return 0
	fi
	cp -p "$f" "${f}.prev"
	chmod 600 "${f}.prev"
	local tmp
	tmp=$(mktemp "${f}.XXXXXX")
	chmod 600 "$tmp"
	if grep -qE "^${key}=" "$f"; then
		awk -v k="$key" -v v="$value" '
			BEGIN { FS=OFS="=" }
			$1==k { print k"="v; replaced=1; next }
			{ print }
			END { if (!replaced) print k"="v }' "$f" >"$tmp"
	else
		cat "$f" >"$tmp"
		printf '%s=%s\n' "$key" "$value" >>"$tmp"
	fi
	mv "$tmp" "$f"
	chmod 600 "$f"
	log "updated $f: ${key}=$(redact "$value")"
}

restore_env_file() {
	local f="$CRM_DEPLOY_ENV_FILE"
	if [[ ! -f "${f}.prev" ]]; then
		warn "no previous env file at ${f}.prev — nothing to restore"
		return 0
	fi
	if (( MODE_DRY_RUN == 1 )); then
		log "[dry-run] would restore ${f}.prev → $f"
		return 0
	fi
	cp -p "${f}.prev" "$f"
	chmod 600 "$f"
	log "restored ${f}.prev → $f"
}

run_redeploy() {
	local cmd="${CRM_REDEPLOY_CMD:-}"
	if [[ -z "$cmd" ]]; then
		cmd=$(default_redeploy_for "$SECRET_NAME") \
			|| die "internal: no redeploy command for $SECRET_NAME" 1
	fi
	if (( MODE_DRY_RUN == 1 )); then
		log "[dry-run] would run: $cmd"
		return 0
	fi
	log "running redeploy: $cmd"
	# shellcheck disable=SC2086
	bash -c "$cmd"
}

# read_secret_stdin — reads the new secret value from stdin with echo
# disabled (only when stdin is a TTY). Echo stays off for the secret
# read; the prompt itself goes to stderr.
read_secret_stdin() {
	local prompt="$1"
	local value
	if [[ -t 0 ]]; then
		# Print prompt to stderr; -s suppresses echo; -r preserves backslashes.
		read -rsp "$prompt: " value
		echo >&2
	else
		# Non-interactive (CI/dry-run): read one line, no prompt.
		read -r value
	fi
	if [[ -z "$value" ]]; then
		die "empty value not allowed" 64
	fi
	printf '%s' "$value"
}

# validate_after_redeploy — runs a provider-appropriate smoke check.
# Failures cause main() to emit a 'failed' audit row and exit 1.
validate_after_redeploy() {
	local url="${CRM_HEALTH_URL:-http://127.0.0.1:8080/health}"
	local timeout="${CRM_VALIDATE_TIMEOUT:-60}"
	local elapsed=0
	if (( MODE_DRY_RUN == 1 )); then
		log "[dry-run] would validate GET $url"
		return 0
	fi
	# Generic health check covers the worker-restart case too because
	# /health stays the same; provider-specific deep checks live in
	# the runbook (the operator runs them by hand after the cycle).
	while (( elapsed < timeout )); do
		if curl -fsS -o /dev/null "$url"; then
			log "validation OK: GET $url"
			return 0
		fi
		sleep 2
		elapsed=$((elapsed + 2))
	done
	die "validation failed: $url did not return 200 within ${timeout}s" 1
}

# ----------------------------------------------------------------------
# Argument parsing + main
# ----------------------------------------------------------------------

usage() {
	sed -n '2,38p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
}

parse_args() {
	while [[ $# -gt 0 ]]; do
		case "$1" in
			--dry-run)  MODE_DRY_RUN=1 ;;
			--rollback) MODE_ROLLBACK=1 ;;
			-h|--help)  usage; exit 0 ;;
			--*)        die "unknown flag: $1" 64 ;;
			*)
				if [[ -z "$SECRET_NAME" ]]; then
					SECRET_NAME="$1"
				else
					die "unexpected extra argument: $1" 64
				fi
				;;
		esac
		shift
	done
	if [[ -z "$SECRET_NAME" ]]; then
		die "missing required argument: <name>" 64
	fi
}

main() {
	parse_args "$@"

	if ! is_supported_name "$SECRET_NAME"; then
		die "unknown secret name: $SECRET_NAME (see docs/ops/secrets-rotation.md)" 64
	fi

	require_env CRM_OPS_ACTOR_USER_ID
	if ! validate_actor_uuid "$CRM_OPS_ACTOR_USER_ID"; then
		die "CRM_OPS_ACTOR_USER_ID does not look like a UUID" 64
	fi
	require_cmd curl

	if (( MODE_ROLLBACK == 1 )); then
		emit_audit "$SECRET_NAME" "rollback_started"
		restore_env_file
		run_redeploy
		emit_audit "$SECRET_NAME" "failed" ',"reason":"rollback_invoked"'
		exit 2
	fi

	local env_key
	env_key=$(env_key_for "$SECRET_NAME")

	emit_audit "$SECRET_NAME" "started"

	local new_value
	new_value=$(read_secret_stdin "Paste new value for $env_key")

	update_env_file "$env_key" "$new_value"
	# Scrub the value from the local shell as soon as it's on disk.
	new_value=""

	run_redeploy
	if ! validate_after_redeploy; then
		emit_audit "$SECRET_NAME" "failed" ',"reason":"validation_failed"'
		exit 1
	fi
	emit_audit "$SECRET_NAME" "completed"

	cat <<EOF >&2
[update-config] $SECRET_NAME rotation completed.
NEXT STEP — revoke the OLD value in the provider's UI:
  openrouter    → https://openrouter.ai/account → API keys → revoke previous
  pagarme       → https://dashboard.pagar.me → Account → API keys → revoke
  slack-alerts  → Slack admin → Apps → Incoming Webhooks → delete previous
EOF
}

if [[ "${UPDATE_CONFIG_LIB_ONLY:-0}" != "1" ]]; then
	main "$@"
fi
