package llmcustomer

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"strings"
	"sync"
	"time"

	"github.com/google/uuid"

	"github.com/pericles-luz/crm/internal/inbox"
)

// Adapter is the fakellm carrier adapter. It bridges the operator's
// outbound channel (inbox.OutboundChannel.SendMessage) and the inbox's
// inbound channel use-case (inbox.InboundChannel.HandleInbound) so a
// single operator turn produces, after a small delay, a customer turn
// generated by a PersonaLLM. Adapter is safe for concurrent use across
// HTTP goroutines and across the per-reply scheduling goroutines it
// owns; per-tenant turn history is protected by an internal mutex.
//
// Lifetime: New starts the adapter's lifetime context and a sync.WaitGroup
// for in-flight reply goroutines. Stop cancels the context and waits for
// every in-flight goroutine to finish; Drain waits without cancelling.
// Both are idempotent so wiring code can defer Stop without ceremony.
type Adapter struct {
	downstream inbox.InboundChannel
	llm        PersonaLLM

	replyDelay time.Duration
	logger     *slog.Logger
	nowFn      func() time.Time
	newIDFn    func() string

	ctx    context.Context
	cancel context.CancelFunc
	wg     sync.WaitGroup

	mu           sync.Mutex
	history      map[uuid.UUID][]Turn
	bootstrapped map[uuid.UUID]struct{}
	stopped      bool
}

// Config is the constructor argument bundle. Downstream and LLM are
// required; the rest carry sensible production defaults but are
// overridable for tests (e.g. ReplyDelay=0, deterministic IDGen/Now).
type Config struct {
	// Downstream is the inbox.InboundChannel the scheduled customer
	// replies are pushed into. Production wires it to the
	// *usecase.ReceiveInbound singleton.
	Downstream inbox.InboundChannel
	// LLM produces the next customer message given the persona prompt
	// and the recent turn history. Wired to canned.LLM in dev/staging
	// fallback or to the future HTTP impl (SIN-63793 W3) in production
	// fake-channel mode.
	LLM PersonaLLM
	// ReplyDelay is the wall-clock delay between an operator's
	// outbound SendMessage and the scheduled customer inbound being
	// pushed downstream. Zero is allowed (synchronous-looking in tests);
	// production wiring picks ~500ms-1s so the operator UI has time to
	// finish rendering the outgoing message before the reply lands.
	ReplyDelay time.Duration
	// Logger is the structured logger used for scheduler bookkeeping
	// (LLM errors, dropped replies). nil falls back to slog.Default.
	Logger *slog.Logger
	// Now is the clock used to stamp scheduled InboundEvents'
	// OccurredAt. nil falls back to time.Now (UTC).
	Now func() time.Time
	// IDGen produces the channel-side identifier of each
	// adapter-generated message (operator outbound + scheduled
	// customer inbound). The default is uuid.NewString — tests
	// override with a deterministic counter.
	IDGen func() string
}

// New validates the config and returns a ready Adapter. Any nil
// required dependency is a programming error caught at construction so
// the process crashes before serving the first request.
func New(cfg Config) (*Adapter, error) {
	if cfg.Downstream == nil {
		return nil, errors.New("llmcustomer: Downstream is nil")
	}
	if cfg.LLM == nil {
		return nil, errors.New("llmcustomer: LLM is nil")
	}
	if cfg.ReplyDelay < 0 {
		return nil, errors.New("llmcustomer: ReplyDelay must be >= 0")
	}
	logger := cfg.Logger
	if logger == nil {
		logger = slog.Default()
	}
	nowFn := cfg.Now
	if nowFn == nil {
		nowFn = func() time.Time { return time.Now().UTC() }
	}
	idGen := cfg.IDGen
	if idGen == nil {
		idGen = uuid.NewString
	}
	ctx, cancel := context.WithCancel(context.Background())
	return &Adapter{
		downstream:   cfg.Downstream,
		llm:          cfg.LLM,
		replyDelay:   cfg.ReplyDelay,
		logger:       logger.With("component", "llmcustomer"),
		nowFn:        nowFn,
		newIDFn:      idGen,
		ctx:          ctx,
		cancel:       cancel,
		history:      make(map[uuid.UUID][]Turn),
		bootstrapped: make(map[uuid.UUID]struct{}),
	}, nil
}

// Channel returns the carrier-channel identifier this adapter speaks
// for. Wiring code uses it to register the adapter in the per-channel
// outbound dispatcher.
func (a *Adapter) Channel() string { return ChannelName }

// Bootstrap ensures the synthetic contact + open conversation pair
// exists for tenantID by injecting a single customer-side inbound
// event. The injection runs through Downstream.HandleInbound, so the
// inbox use-case owns the contact / conversation create-or-find
// pipeline and dedup-ledger semantics — Adapter does not poke any
// storage adapter directly.
//
// Idempotency is two-layer:
//
//   - Lifetime: an in-memory bootstrapped set short-circuits repeat
//     calls for the same tenantID in the same Adapter lifetime so the
//     LLM is only consulted once per tenant per process.
//   - Persistence: the channel-side identifier is the stable string
//     "fakellm:bootstrap:<tenantID>" so even across process restarts
//     the inbound dedup ledger collapses duplicate Bootstrap calls
//     into a single persisted message and conversation.
func (a *Adapter) Bootstrap(ctx context.Context, tenantID uuid.UUID) error {
	if tenantID == uuid.Nil {
		return errors.New("llmcustomer: Bootstrap requires non-nil tenantID")
	}
	a.mu.Lock()
	if _, ok := a.bootstrapped[tenantID]; ok {
		a.mu.Unlock()
		return nil
	}
	if a.stopped {
		a.mu.Unlock()
		return errors.New("llmcustomer: adapter is stopped")
	}
	historySnapshot := snapshotTurns(a.history[tenantID])
	a.mu.Unlock()

	body, err := a.llm.NextCustomerMessage(ctx, PersonaV1, historySnapshot)
	if err != nil {
		return fmt.Errorf("llmcustomer: bootstrap LLM call: %w", err)
	}
	body = strings.TrimSpace(body)
	if body == "" {
		return errors.New("llmcustomer: bootstrap LLM returned empty body")
	}

	ev := inbox.InboundEvent{
		TenantID:          tenantID,
		Channel:           ChannelName,
		ChannelExternalID: fmt.Sprintf("%s:bootstrap:%s", ChannelName, tenantID.String()),
		SenderExternalID:  SyntheticContactExternalID,
		SenderDisplayName: SyntheticContactDisplayName,
		Body:              body,
		OccurredAt:        a.nowFn(),
	}
	if err := a.HandleInbound(ctx, ev); err != nil {
		return fmt.Errorf("llmcustomer: bootstrap inbound: %w", err)
	}

	a.mu.Lock()
	a.bootstrapped[tenantID] = struct{}{}
	a.mu.Unlock()
	return nil
}

// SendMessage implements inbox.OutboundChannel. It records the
// operator's turn in the per-tenant history, returns a freshly
// generated channel-external-id for the operator's outbound row, and
// schedules an asynchronous follow-up: after ReplyDelay, the adapter
// asks PersonaLLM for the customer's next line and pushes it back into
// the inbox via HandleInbound. The follow-up goroutine is bound to the
// Adapter's lifetime context — Stop cancels both the pre-LLM delay and
// any in-flight LLM call.
//
// The send itself never blocks on the LLM: the operator HTMX handler
// returns as soon as the outbound row is persisted, and the customer's
// reply arrives later via the existing status-polling path.
func (a *Adapter) SendMessage(ctx context.Context, m inbox.OutboundMessage) (string, error) {
	if err := validateOutbound(m); err != nil {
		return "", err
	}

	a.mu.Lock()
	if a.stopped {
		a.mu.Unlock()
		return "", errors.New("llmcustomer: adapter is stopped")
	}
	a.history[m.TenantID] = append(a.history[m.TenantID], Turn{
		Role: TurnRoleOperator,
		Body: m.Body,
	})
	historySnapshot := snapshotTurns(a.history[m.TenantID])
	a.mu.Unlock()

	operatorID := a.newIDFn()
	a.scheduleReply(m.TenantID, m.ConversationID, historySnapshot)
	return operatorID, nil
}

// HandleInbound implements inbox.InboundChannel. It records the
// inbound body as a customer turn for the event's tenant history and
// forwards the event to the downstream inbox use-case. External
// callers (tests, future webhook-style integrations) can invoke it to
// inject customer-side traffic without going through SendMessage.
func (a *Adapter) HandleInbound(ctx context.Context, ev inbox.InboundEvent) error {
	if ev.TenantID == uuid.Nil {
		return errors.New("llmcustomer: HandleInbound requires non-nil TenantID")
	}
	if !strings.EqualFold(ev.Channel, ChannelName) {
		return fmt.Errorf("llmcustomer: HandleInbound rejects channel %q (want %q)", ev.Channel, ChannelName)
	}
	a.mu.Lock()
	a.history[ev.TenantID] = append(a.history[ev.TenantID], Turn{
		Role: TurnRoleCustomer,
		Body: ev.Body,
	})
	a.mu.Unlock()
	return a.downstream.HandleInbound(ctx, ev)
}

// ResetConversation clears the adapter's in-memory state for tenantID so
// a reset of the training conversation (SIN-65392) starts the simulator
// fresh: the per-tenant turn history is dropped and the bootstrapped flag
// is cleared, so the next GET /inbox re-bootstraps a new greeting and the
// next operator turn drives the LLM against an empty history.
//
// It is the channel half of usecase.ResetConversation — the use case
// deletes the message rows in Postgres, then calls this so the in-memory
// twin cannot desync from the now-empty thread.
//
// v1 keys history + bootstrapped by tenant (one persona per tenant — see
// persona_llm.go), so the conversationID argument is accepted for the
// ConversationResetter contract but the reset is tenant-wide; with a
// single training conversation per tenant the two are equivalent. The
// adapter deliberately does NOT re-inject a greeting here: the reset's
// contract is "the thread is now empty", and the lazy bootstrap path
// (bootstrapOnList*) re-seeds the greeting on the next list load.
//
// Idempotent and safe to call after Stop: it only mutates maps under the
// mutex and never schedules work.
func (a *Adapter) ResetConversation(_ context.Context, tenantID, _ uuid.UUID) error {
	if tenantID == uuid.Nil {
		return errors.New("llmcustomer: ResetConversation requires non-nil tenantID")
	}
	a.mu.Lock()
	delete(a.history, tenantID)
	delete(a.bootstrapped, tenantID)
	a.mu.Unlock()
	return nil
}

// Drain blocks until every in-flight scheduled reply goroutine has
// finished. It does NOT cancel the adapter — useful in tests that want
// to assert post-condition without tearing the adapter down. Idempotent.
func (a *Adapter) Drain() { a.wg.Wait() }

// Stop cancels the adapter's lifetime context — interrupting any
// pre-LLM delay and any in-flight LLM call — and waits for every
// in-flight reply goroutine to return. After Stop, SendMessage /
// Bootstrap return an error; further Stop / Drain calls are no-ops.
func (a *Adapter) Stop() {
	a.mu.Lock()
	if a.stopped {
		a.mu.Unlock()
		return
	}
	a.stopped = true
	a.mu.Unlock()
	a.cancel()
	a.wg.Wait()
}

// scheduleReply is the goroutine launcher. It snapshots the history at
// schedule time (already done by the caller) so the customer reply is
// computed against the conversation as the operator saw it, even if
// new turns land before the LLM returns.
func (a *Adapter) scheduleReply(tenantID, conversationID uuid.UUID, history []Turn) {
	a.wg.Add(1)
	go func() {
		defer a.wg.Done()
		if a.replyDelay > 0 {
			select {
			case <-time.After(a.replyDelay):
			case <-a.ctx.Done():
				return
			}
		} else if a.ctx.Err() != nil {
			return
		}

		body, err := a.llm.NextCustomerMessage(a.ctx, PersonaV1, history)
		if err != nil {
			a.logger.WarnContext(a.ctx, "fakellm reply dropped: llm error",
				"tenant_id", tenantID.String(),
				"conversation_id", conversationID.String(),
				"err", err.Error(),
			)
			return
		}
		body = strings.TrimSpace(body)
		if body == "" {
			a.logger.WarnContext(a.ctx, "fakellm reply dropped: empty body",
				"tenant_id", tenantID.String(),
				"conversation_id", conversationID.String(),
			)
			return
		}

		ev := inbox.InboundEvent{
			TenantID:          tenantID,
			Channel:           ChannelName,
			ChannelExternalID: a.newIDFn(),
			SenderExternalID:  SyntheticContactExternalID,
			SenderDisplayName: SyntheticContactDisplayName,
			Body:              body,
			OccurredAt:        a.nowFn(),
		}
		if err := a.HandleInbound(a.ctx, ev); err != nil {
			a.logger.WarnContext(a.ctx, "fakellm reply dropped: downstream error",
				"tenant_id", tenantID.String(),
				"conversation_id", conversationID.String(),
				"err", err.Error(),
			)
		}
	}()
}

// validateOutbound runs the per-call argument checks for SendMessage.
// Adapter-side validation duplicates the inbox use-case's checks only
// to fail fast with a meaningful error before any goroutine is spawned.
func validateOutbound(m inbox.OutboundMessage) error {
	if m.TenantID == uuid.Nil {
		return errors.New("llmcustomer: SendMessage requires non-nil TenantID")
	}
	if m.ConversationID == uuid.Nil {
		return errors.New("llmcustomer: SendMessage requires non-nil ConversationID")
	}
	if !strings.EqualFold(m.Channel, ChannelName) {
		return fmt.Errorf("llmcustomer: SendMessage rejects channel %q (want %q)", m.Channel, ChannelName)
	}
	if strings.TrimSpace(m.Body) == "" {
		return errors.New("llmcustomer: SendMessage requires non-empty Body")
	}
	return nil
}

// snapshotTurns returns a defensive copy so concurrent History mutation
// cannot race with an LLM call already in flight against the snapshot.
func snapshotTurns(turns []Turn) []Turn {
	if len(turns) == 0 {
		return nil
	}
	out := make([]Turn, len(turns))
	copy(out, turns)
	return out
}

// Compile-time guards: Adapter satisfies both inbox-side ports so
// composition-root code can wire it on either face of the seam.
var (
	_ inbox.OutboundChannel = (*Adapter)(nil)
	_ inbox.InboundChannel  = (*Adapter)(nil)
)
